version: '3'
services:
  db:
    image: 'mysql'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
